### ISSUE TITLE
Any code for d3-axis?

### ISSUE THREAD

**Issue by walter211** [hswolff/BetterWeather#1]
Hi, could you show some code for adding axis by using d3-axis?

**Comment by hswolff** [comment]
Hey @walter211! I never had good luck getting d3-axis to play nicely with React Native. Instead I just used plain `<View />` components. Check out the [Axis section](http://hswolff.com/blog/react-native-art-and-d3/) on my blog post for an explanation on how!

Going to close as I don't have any code (or any success) on using d3-axis with React Native.
