### ISSUE TITLE
Cannot run this project

### ISSUE THREAD

**Issue by alexmngn** [hswolff/BetterWeather#3]
Hello,
I tried to run this demo for iOS but I can't make it to work.

I use the latest version of `react-native-cli`
`react-native-cli: 1.3.0`

If I run it from Xcode, I get the following error:

<img width="1515" alt="screen shot 2016-12-07 at 18 23 44" src="https://cloud.githubusercontent.com/assets/4203845/20965897/642ced64-bcaa-11e6-80ed-07d2d744c32d.png">

If I run it from terminal, I get this:

<img width="1040" alt="screen shot 2016-12-07 at 18 25 16" src="https://cloud.githubusercontent.com/assets/4203845/20965927/87784cd2-bcaa-11e6-963b-4dcb8706f446.png">

Any idea?
Thanks

**Comment by hswolff** [comment]
You're absolutely correct. I wasn't able to get it working locally anymore!

Just upgraded to latest version of React Native and I got it to work.

FYI my environment:

```
$ react-native --version
react-native-cli: 1.3.0
react-native: 0.39.0
```

Xcode: Version 8.1 (8B62)

Did not try running Android. Fingers crossed it still works.

Thanks so much for opening the helpful issue!
